### ISSUE TITLE
Attribute "intensity" has already been defined

### ISSUE THREAD

**Issue by PatrickDattilio** [nvanbenschoten/motion#14]
It appears both shimmer-android and your library and define the attribute "intensity". Could you prefix your libraries attributes as per https://code.google.com/p/android/issues/detail?id=22576?

This prevents the following compile time error.
Error:(2) Attribute "intensity" has already been defined

**Comment by nvanbenschoten** [comment]
I have just published [v1.1.1](https://github.com/nvanbenschoten/motion/releases/tag/v1.1.1), which should resolve this issue by prefixing all attributes with "motion".
